name: Docker Image CI

on:
  push:
    branches:
      - '*'
  pull_request:
    branches:
      - '*'

jobs:

  build1:

    name: Vue App

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd app/
        docker run --privileged -d docker:dind
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)

  build2:

    name: Flask App

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Build the Docker image
      run: |
        cd api/
        docker run --privileged -d docker:dind
        docker build . --file Dockerfile --tag my-image-name:$(date +%s)

